# Generated by Django 5.2.7 on 2025-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_first_name', models.CharField(max_length=100)),
                ('Stu_last_name', models.CharField(max_length=100)),
                ('Stu_grade', models.CharField(max_length=50)),
                ('Stu_birth_date', models.DateField()),
            ],
        ),
    ]
