# Generated by Django 5.2.7 on 2025-10-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_first_name', models.CharField(max_length=100)),
                ('tea_last_name', models.CharField(max_length=100)),
                ('tea_subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_birth_date',
            new_name='stu_birth_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_first_name',
            new_name='stu_first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_grade',
            new_name='stu_grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stu_last_name',
            new_name='stu_last_name',
        ),
    ]
