# Generated by Django 5.2.7 on 2025-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_grade_headmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, help_text='Motivo de la ausencia o tardanza, si aplica.', null=True),
        ),
    ]
