# Generated by Django 5.2.7 on 2025-10-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendance_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='reason',
            new_name='justreasonification',
        ),
    ]
