# Generated by Django 5.2.7 on 2025-10-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_reason_attendance_justreasonification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='justreasonification',
            new_name='reason',
        ),
    ]
